#!/bin/bash

git config --local user.name "Daniel Herr"
git config --local user.email "dzherr@gmail.com"

npm install

bundle install

bundle exec rake db:create db:migrate db:seed

heroku logout

rm ~/.ssh/id_*
heroku login
heroku keys:add

heroku git:remote phimail

webpack --watch
