#!/bin/bash

git config --local user.name "Daniel Herr"
git config --local user.email "dzherr@gmail.com"

npm install

bundle install

bundle exec rake db:create db:migrate db:seed

heroku logout

webpack --watch
