var ConversationConstants = {
  getAll : "001_GET_ALL_OF_THE_CONVERSATIONS_FOR_THE_CURRENT_USER_AND_PUT_IN_THE_STORE",
  updateOne: "002_GET_A_CONVERSATION_THAT_HAS_BEEN_SOMEHOW_CHANGED_AND_PUT_IT_IN_THE_STORE_OVERWRITING_THE_ONE_THATS_THERE"
};

module.exports = ConversationConstants;
