var MessageConstants = {
  receiveAll: "004-GET_A_SINGLE_CONVERSATION_WITH_A_NUMBER_OF_MESSAGES_THAT_WILL_BE_DISPLAYED_IN_THE_DETAIL_VIEW",
  receiveOne: "007-RECIEVE_THE_FULL_TEXT_AND_OTHER_DETAILS_OF_A_SINGLE_MESSAGE_THAT_WAS_PROBABLY_ONLY_PARTIALLY_LOADED_THE_FIRST_TIME"
};

module.exports = MessageConstants;
