var PopupConstants = {
  add: "010-TAKE_IN_A_CALLBACK_FUNCTION_THAT_GENERATES_A_POPUP_OR_SOMETHING_AND_ADD_IT_TO_THE_STORE_SO_THAT_EVERYONE_MAY_POLLUTE_THE_USERS_WINDOW_WITH_POPUPS",
  remove: "011-TAKE_THE_CALLBACK_BACK_OUT_OF_THE_STORE_BECAUSE_THE_COMPONENT_UNMOUNTED_OR_SOMETHING"
};

module.exports = PopupConstants;
