#! /usr/bin/env ruby

require('byebug')
string = IO.read("./meno.txt")

array = string.split("\r\n\r\n")
$increments = ['years', 'months', 'days', 'hours', 'minutes', 'seconds']
$time_idx = 0
$time_num = 10.0
$num = 3
$soc = "daemonic#{'#{EMAIL_SIGNATURE}'}"
$meno = "meno#{'#{EMAIL_SIGNATURE}'}"
$boy = "boy#{'#{EMAIL_SIGNATURE}'}"
$anytus = "anytus#{'#{EMAIL_SIGNATURE}'}"
$meno_target = $soc
$soc_target = $meno
$boy_target = [$soc, $meno].join(", ")
$anytus_target = [$soc, $meno].join(", ")
$mnum = 1;
header = <<-HEADER

meno = User.create({fname: "Meno", lname:"of Thessalonia", username: "meno", pass: "12345678"})
boy = User.create({fname:"Slave Boy", lname:"of Meno", username:"boy", pass:"12345678"})
anytus = User.create({fname: "Anytus", lname:"of Athens", username:"anytus", pass:"12345678"})
soc = User.find_by_username('daemonic')

MetCon#{$num} = MetaConversation.create();

Scon#{$num} = soc.conversations.create(title: 'A Question, Socrates', meta_conversation: MetCon#{$num})
Mcon#{$num} = meno.conversations.create(title: 'A Question, Socrates', meta_conversation: MetCon#{$num})
Bcon#{$num} = boy.conversations.create(title: 'A Question, Socrates', meta_conversation: MetCon#{$num})
Acon#{$num} = anytus.conversations.create(title: 'A Question, Socrates', meta_conversation: MetCon#{$num} )


HEADER

array = array.map! do |message|

  temp = message.split(':', 2)
  name = temp[0]
  message = temp[1]

  if message

    if Random.rand > 0.94

      read = $time_idx <= 3;
      min_message = <<-msg

        Scon#{$num}.update({
                             message_timestamp: #{$time_num.floor}.#{$increments[$time_idx]}.ago,
                             read: #{read}
                           }) 
        Mcon#{$num}.update({
                             message_timestamp: #{$time_num.floor}.#{$increments[$time_idx]}.ago,
                             read: #{read}
                           }) 
        Bcon#{$num}.update({
                             message_timestamp: #{$time_num.floor}.#{$increments[$time_idx]}.ago,
                             read: #{read}
                           }) 
        Acon#{$num}.update({
                             message_timestamp: #{$time_num.floor}.#{$increments[$time_idx]}.ago,
                             read: #{read}
                           }) 

msg
                              
      title = message.split(' ').take(6).join(' ')
      $num = $num + 1
      
      min_message = <<-cons
      #{min_message}

      MetCon#{$num} = MetaConversation.create();

      Scon#{$num} = soc.conversations.create(title: \"#{title}\", meta_conversation: MetCon#{$num})
      Mcon#{$num} = meno.conversations.create(title: \"#{title}\", meta_conversation: MetCon#{$num})
      Bcon#{$num} = boy.conversations.create(title: \"#{title}\", meta_conversation: MetCon#{$num})
      Acon#{$num} = anytus.conversations.create(title: \"#{title}\", meta_conversation: MetCon#{$num} )

      cons

      message =  min_message + "body_str = <<-BODY \n" + message
    else
      message = "body_str = <<-BODY \n" + message
    end


    if $time_idx == 6
      $time_num -= (Random.rand)/10 if $time_num > 10
    else
      $time_num -= (Random.rand)/6
      if $time_num <= 1
        $time_num = 12
        $time_idx += 1
      end
    end


    if name == "SOCRATES"
      seed = "msg#{$mnum} = Scon#{$num}.messages.create({\n"
      message.sub!('SOCRATES:', "body_str = <<-BODY \n")
      $source = $soc
      $target = $soc_target
    elsif name == "MENO"
      seed = "msg#{$mnum} = Mcon#{$num}.messages.create({\n"
      message.sub!('MENO:', "body_str = <<-BODY \n")
      $source = $meno
      $target = $meno_target
    elsif name == "ANYTUS"
      seed = "msg#{$mnum} = Acon#{$num}.messages.create({\n"
      message.sub!('ANYTUS:', "body_str = <<-BODY \n")
      $source = $anytus
      $target = $anytus_target
      $soc_target = [$anytus, $meno].join(", ")
      $meno_target = [$soc, $anytus].join(", ")
    elsif name == "BOY"
      seed = "msg#{$mnum} = Bcon#{$num}.messages.create({\n"
      message.sub!('BOY:', "body_str = <<-BODY \n")
      $source = $boy
      $target = $boy_target
      $soc_target = [$boy, $meno].join(", ")
      $meno_target = [$soc, $boy].join(", ")
    else
      seed = ""
      clearseed = true
    end

    seed += <<-seed
    source_address: \"#{$source}\",
    target_address: \"#{$target}\",
    body: body_str,
    created_at: #{$time_num.floor}.#{$increments[$time_idx]}.ago
    })

    msg#{$mnum}.send_msg
    msg#{$mnum}.update({updated_at: #{$time_num.floor}.#{$increments[$time_idx]}.ago})


    seed


    $mnum += 1
    seed = "" if clearseed

    message = message.concat("\nBODY\n\n")
    if seed
      message = message.concat(seed)
    else
      message = min_message
    end
    message
  end
end

string = array.join("\n\n")

File.write("./meno.rb", header + string)
